#!/bin/bash

program="$1"
shift
# -args
shift

while [ "$1" != "-output" ] && [ "$1" != "-output-file" ]; do
  args+=("$1")
  shift
done

if [ "$1" = "-output" ]; then
    shift
    while [ $# -gt 0 ]; do
      expected_output+=("$1")
      shift
    done
elif [ "$1" = "-output-file" ]; then
    shift
    expected_output+=("`cat $1`")
fi

echo "Executing: $program ${args[@]}"
output="`$program "${args[@]}" 2>&1`"
if [ $? -ne 0 ]; then
    echo "Execution failed: $output" 1>&2
    exit 1
fi

if [ "`echo "$output" | xargs`" != "`echo "$expected_output" | xargs`" ]; then
    echo "Output different from expected:" 1>&2
	 diff -Naur <(echo -n "$output") <(echo -n "$expected_output")
    exit 1
fi

echo "$output"
