#!/bin/bash

program="$1"
shift
# -args
shift

while [ "$1" != "-output" ]; do
  args+=("$1")
  shift
done
shift
while [ $# -gt 0 ]; do
  expected_output+=("$1")
  shift
done

echo "Executing: $program ${args[@]}"
output="`$program "${args[@]}" 2>&1`"
if [ $? -ne 0 ]; then
    echo "Execution failed: $output" 1>&2
    exit 1
fi

if [ "$output" != "$expected_output" ]; then
    echo "Output different from expected:" 1>&2
    echo "$output" 1>&2
    echo "=======" 1>&2
    echo "$expected_output" 1>&2
    exit 1
fi

echo "$output"
